BZ#1763837 - properly decode fetched ssh keys on Python3
otherwise, you end up with errors like

    TypeError: 'in <string>' requires string as left operand, not bytes